//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GizaTraffic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GizaTraffic.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل رقم كارت العائلة.
        /// </summary>
        internal static string EnterFamilyCardNo {
            get {
                return ResourceManager.GetString("EnterFamilyCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل أطفال العائلة.
        /// </summary>
        internal static string EnterFamilyKids {
            get {
                return ResourceManager.GetString("EnterFamilyKids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل اسم العائلة.
        /// </summary>
        internal static string EnterFamilyName {
            get {
                return ResourceManager.GetString("EnterFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل رقم العائلة.
        /// </summary>
        internal static string EnterFamilyNo {
            get {
                return ResourceManager.GetString("EnterFamilyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل اسم الأب.
        /// </summary>
        internal static string EnterFatherName {
            get {
                return ResourceManager.GetString("EnterFatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد عائلة بهذا الرقم.
        /// </summary>
        internal static string NoFamilyWithThisNo {
            get {
                return ResourceManager.GetString("NoFamilyWithThisNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        internal static string SaveSuccessfull {
            get {
                return ResourceManager.GetString("SaveSuccessfull", resourceCulture);
            }
        }
    }
}
