//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProgramMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgramMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utilities.Resources.ProgramMessages", typeof(ProgramMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في برنامج عرض التقارير.
        /// </summary>
        internal static string ErrMesCrystalRepInstallation {
            get {
                return ResourceManager.GetString("ErrMesCrystalRepInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم ظهور هذا الخطأ.
        /// </summary>
        internal static string ErrMesErrorOccured {
            get {
                return ResourceManager.GetString("ErrMesErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الذاكرة ممتلئة من فضلك أغلق بعض البرامج.
        /// </summary>
        internal static string ErrMesMemoryFull {
            get {
                return ResourceManager.GetString("ErrMesMemoryFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن الكتابة هنا.
        /// </summary>
        internal static string MesCantWriteInField {
            get {
                return ResourceManager.GetString("MesCantWriteInField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامج تسجيل حجز المركبات.
        /// </summary>
        internal static string MesHeader {
            get {
                return ResourceManager.GetString("MesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن الكتابة باللغة العربية هنا.
        /// </summary>
        internal static string MesNoArabicInput {
            get {
                return ResourceManager.GetString("MesNoArabicInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن الكتابة باللغة الانجليزية هنا.
        /// </summary>
        internal static string MesNoEnglishInput {
            get {
                return ResourceManager.GetString("MesNoEnglishInput", resourceCulture);
            }
        }
    }
}
